### ISSUE TITLE
Basic auth integration for newspaper styled subscriptions

### ISSUE THREAD

**Issue by Pelle-Jensen** [infosoftas/info-subscription-doc#63]
I'm currently in the process of integrating Info-subscription for a online newspaper subscription system.

The integration process started slow due to not having a grasp of how the different systems piece together, and what pieces i actually need to get what i want done.
I've had to look to existing infosub newspapers to piece together endpoints and information on how a subscription is created and maintained step by step.

The quick start guide is everything most people will need, but adding a few basic pieces of information could make the integration significantly more seamless. In its current form, the documentation makes the integration process seem more daunting/complicated than it actually is (If you just want basic subscription functionality where most of the end user management will be done in the Infosoft environment)

So all I am looking to add to the documentation is a basic step-by-step flow guide that includes examples of:
- How the customer have to press a link to get to their desired product
- How the registration process works for the customer
- Where the user can access and manage their subscription
- Where the merchant will manage subscriptions in prod env
- Basic server-side auth flow
- and a few other points i've had to ask about

I feel like this is information that should be readily available to anyone looking to integrate Info-Subscription.
This would speed up integration for future developers, and lessen your workload on the email correspondence side of things (These points have been the main topic of my emails)

**Comment by esbenbach** [comment]
Hi Pelle.

Thanks for the feedback. We will try to incoporate it into a more specific quick start that points to some of these items.
The main issue here is that many of the questions you are asking are/should be covered in the user documentation (at least thats the idea), and we attempt to avoid overlapping too much in the developer docs (though it can't be avoided). 
Though as a third party developer with no knowledge of the system I understand we can do much better here!

One thing im curious about though: 

**Basic server-side auth flow**
We currently support OAuth2 and OIDC by utilizing ADB2C as the IdP (or Auth0 for some tenants).
The `client_credentials` flow is for headless/server2server authentication. 
All other flows are designed to be used with some user interaction where the browser/device is somehow needed to confirm access, however the `authorization code` flow is specifically designed to work with a backend/server and the user at the same time (https://openid.net/specs/openid-connect-core-1_0.html#CodeFlowAuth).

This is the code flow outlined in the `Authentication and Authorization` quick start basically.

I know OAuth2 and OIDC can be at times complicated entities with annoying nuiances between IdPs. 
So I am trying to understand what you are missing in the docs here.

**Comment by esbenbach** [comment]
Just a small update here. I have raised a PR #66 that attempts to solve some of the issues mentioned here.

It includes a small 3 step overview of what is required for a typical integration (self-service link, sales processing link + configuration options, authorization to consume products), together with the links to the sections that the describes each process.
Hopefully this should make everything a bit clearer.

We are however not going to address everything: 
- Merchant management, we assume this is taken care of by the tenant onboarding and user documentation we currently have.
- Visual guidance/description of the subscriber ordering process. This should be taken care of by the user docs. We have however added on the backlog that said user docs should be expanded upon with a more thorough description.


Thanks again for the feedback, much appreciated.
